### ISSUE TITLE
Experience stuck in Quest3 after doff the for 1 minute

### ISSUE THREAD

**Issue by zjm-meta** [CadenzaVR/cadenza#19]
Hello this is Jianmin from Meta here. We just did some tests about this experience in Quest3 and the experience would stuck in a non-recoverable status after doff the headset for 1 minute during the experience. The console error log I saw was "Not allowed to load local resource: chrome://resources/optimistic/Optimistic_Text_W_Lt.woff2", source: chrome-error://chromewebdata/ (3216).

We have to remove this experience from our new tab page because of this issue. Feel free to contact us if you have it fixed. Thanks!

**Comment by devmaxxing** [comment]
Hi @zjm-meta. Unfortunately I do not have a Quest 3 to reproduce this issue and the file mentioned in the console error doesn't appear to be present in the codebase. Can this be reproduced on the Quest 2? Do you have information on when users first started to report this bug and on which device(s)?

**Comment by zjm-meta** [comment]
It does repro on Quest 2. You can just click the power button once to put the headset in sleep for about 1 minute to repro. I did notice that it doesn't crash if I wake the device up very quickly (like in ~10 secs).

We started seeing this bug on June 5th 2024.

**Comment by devmaxxing** [comment]
@zjm-meta Thanks! I was able to reproduce the issue I think (black screen when I turned the headset back on but was able to get out of it by pressing the oculus home button). I just pushed something to production which seems to have fixed the issue when I tested again.

**Comment by zjm-meta** [comment]
Hello. I can see some error logs in the console like 

GET https://cookies.andbeyond.media/3b3bd4177dc9cc764d515f98ec9e416d.gif?puid=6a45b36b-55d4-53dc-aa2e-f016cc9d2adb net::ERR_CONNECTION_TIMED_OUT

GET https://bc-sync.com/adyoulike_sync_80233?redirect_url=https%3A%2F%2Fvisitor-us-west-2.omnitagjs.com%2Fvisitor%2Fsync%3Fname%3DBIZZCLICK%26ttl%3D720%26uid%3De18370a9401ca57378a3afaa926ec2e5%26visitor%3D%26gdpr%3D0%26gdpr_consent%3D&gdpr=0&gdpr_consent= net::ERR_CONNECTION_TIMED_OUT

ClassicGameState.ts:227 Uncaught TypeError: Cannot read properties of undefined (reading 'shift')
    at a.update (ClassicGameState.ts:227:31)
    at c.update (GameController.ts:98:20)
    at n.tick (GameController.ts:77:25)
    at v.tick (a-scene.js:697:30)
    at v.render (a-scene.js:743:32)
    at bind.js:12:17
    at three.module.js:28350:35
    at r (three.module.js:12556:3)

From what I observed, looks like the browser entered the WebXR session successfully but the game doesn't draw any frame which caused the experience stuck in the 3-dot loading state. This could be related to the exception above. This happens after I click the power button and let the device sleep for ~5mins and click the power button to reopen it again. I would suggest you to implement some retry logic or just let the page refresh after ~5mins since the user may not be playing the game anymore. 

For reference Moonrider doesn't have this behavior on my side after 5mins sleep (with and without the music being played).

**Comment by devmaxxing** [comment]
@zjm-meta on the Quest 2 I think I was still able to replicate the issue on Moonrider so just to be safe I've pushed a change where putting the headset to sleep will pause the game and exit the XR session.

**Comment by zjm-meta** [comment]
Cool. I just tested on my side and it's working for me. I will start a new QA test session and add Cadenza back to our new tab page once it passed. Thanks for the follow up!
